### PR TITLE
Merge branch master

### PR DESCRIPTION
**Pull request by Jacalz**
- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).

Test Plan:

### CODE REVIEW

**Comment by luixxiul** [comment]
This PR changed the history of commits which do not have its own PR: eg https://github.com/brave/browser-laptop/commit/6ea3ca4d218982e9de95df5f6fa0812d951c6be4 https://github.com/brave/browser-laptop/commit/96b2f070fa0a69c61a0019a063f9e36e7d558635

**Comment by Jacalz** [comment]
Did I mess something up for you guys, I just wanted to get my fork up to date 😅 Huge sorry if I did something stupid 😬

**Comment by luixxiul** [comment]
It's not a big deal :-)

If you want to update your local repo, I think this should work fine:

````
git checkout master
git remote add upstream https://github.com/brave/browser-laptop
git fetch upstream
git rebase upstream/master
````
(It is ok to rename `upstream` to anything you want.)

By doing so you won't have to create a PR each time to update your local repo.

I'm not quite sure if this work but you might want to delete your repo and give another try to remove `#1`s from those commits.

**Comment by luixxiul** [comment]
git checkout master - change your local branch to `master`

git remote add upstream https://github.com/brave/browser-laptop - add the official repo as a remote source

git fetch upstream - fetch data from the remote source

git rebase upstream/master - update your local `master` to the latest status of `upstream`'s master

git push - update your remote branch

Does it make clear to you?

**Comment by Jacalz** [comment]
Puh, great to know that I didn't do something totally stupid and thanks for the advice 😝

**Comment by Jacalz** [comment]
Well I prefer using github.com with a user interface but i will give it a chance 😅

**Pull request merged**
